#!/usr/bin/env php
<?php

set_time_limit(0);

require_once __DIR__.DIRECTORY_SEPARATOR.'app_init.php';

use Symfony\Component\Console\Application;
use TonicForHealth\ReportAggregator\Command\TestRailReportAggregator;

$app = new Application();
$app->add(new TestRailReportAggregator($container));
$app->run();